-- Seed canonical reason codes into eod_reason_codes.
-- Safe to rerun: uses ON DUPLICATE KEY UPDATE for description/severity/category/is_active.

INSERT INTO eod_reason_codes (`code`, `category`, `description`, `severity`, `is_active`) VALUES
('RUN_COVERAGE_LOW', 'RUN', 'Rasio cakupan untuk requested date berada di bawah ambang minimum yang dikunci.', 'HARD', 1),
('RUN_INDICATORS_MISSING', 'RUN', 'Artefak indikator wajib atau himpunan row indikator untuk requested date tidak tersedia.', 'HARD', 1),
('RUN_ELIGIBILITY_MISSING', 'RUN', 'Snapshot eligibility untuk requested date tidak tersedia.', 'HARD', 1),
('RUN_HASH_MISSING', 'RUN', 'Satu atau lebih content hash wajib tidak tersedia pada saat finalisasi.', 'HARD', 1),
('RUN_HASH_FAILED', 'RUN', 'Proses perhitungan hash gagal atau menghasilkan output yang tidak dapat digunakan.', 'HARD', 1),
('RUN_SEAL_PRECONDITION_FAILED', 'RUN', 'Proses seal dijalankan sebelum seluruh prasyarat yang dikunci terpenuhi.', 'HARD', 1),
('RUN_SEAL_WRITE_FAILED', 'RUN', 'Metadata seal gagal ditulis dengan sukses.', 'HARD', 1),
('RUN_FINALIZE_BEFORE_CUTOFF', 'RUN', 'Final success dicoba sebelum kebijakan cutoff mengizinkannya.', 'HARD', 1),
('RUN_LOCK_CONFLICT', 'RUN', 'Terjadi konflik kepemilikan proses atau duplicate writer pada tahap hash, seal, atau finalize.', 'HARD', 1),
('RUN_SOURCE_TIMEOUT', 'RUN', 'Source mengalami timeout dan kebijakan retry sudah dijalankan atau habis.', 'WARN', 1),
('RUN_SOURCE_RATE_LIMIT', 'RUN', 'Source terkena pembatasan rate limit dan memengaruhi proses akuisisi data.', 'WARN', 1),
('RUN_SOURCE_AUTH_ERROR', 'RUN', 'Kegagalan autentikasi source atau kesalahan credential/config menghambat akuisisi data.', 'HARD', 1),
('RUN_SOURCE_RESPONSE_CHANGED', 'RUN', 'Terdeteksi perubahan schema atau kontrak response dari source.', 'HARD', 1),
('RUN_SOURCE_PARTIAL_COVERAGE', 'RUN', 'Source mengembalikan cakupan simbol yang tidak lengkap untuk requested date.', 'WARN', 1),
('RUN_SOURCE_MALFORMED_PAYLOAD', 'RUN', 'Payload dari source tidak dapat dinormalisasi dengan aman.', 'HARD', 1),
('BAR_DUPLICATE_SOURCE_ROW', 'BAR', 'Terdapat lebih dari satu row source yang memetakan ke (trade_date, ticker_id) yang sama sehingga perlu pemilihan winner secara deterministik.', 'WARN', 1),
('BAR_INVALID_OHLC_ORDER', 'BAR', 'Nilai OHLC yang diterima melanggar aturan urutan canonical.', 'HARD', 1),
('BAR_NON_POSITIVE_PRICE', 'BAR', 'Nilai harga yang diterima bernilai nol atau negatif pada field yang seharusnya positif.', 'HARD', 1),
('BAR_NEGATIVE_VOLUME', 'BAR', 'Nilai volume yang diterima bernilai negatif.', 'HARD', 1),
('BAR_MISSING_REQUIRED_FIELD', 'BAR', 'Satu atau lebih field source yang wajib tidak tersedia.', 'HARD', 1),
('IND_INSUFFICIENT_HISTORY', 'INDICATOR', 'Riwayat trading-day yang dibutuhkan belum cukup untuk perhitungan indikator secara deterministik.', 'WARN', 1),
('IND_MISSING_DEPENDENCY_BAR', 'INDICATOR', 'Canonical bar yang dibutuhkan dalam rantai trading-day tidak tersedia.', 'HARD', 1),
('IND_INVALID_BAR_INPUT', 'INDICATOR', 'Input canonical bar yang digunakan untuk menghitung indikator tidak valid.', 'HARD', 1),
('IND_COMPUTE_ERROR', 'INDICATOR', 'Perhitungan indikator gagal karena kesalahan logika atau runtime.', 'HARD', 1),
('ELIG_MISSING_BAR', 'ELIGIBILITY', 'Ticker yang termasuk coverage universe tidak memiliki canonical valid bar untuk requested date.', 'WARN', 1),
('ELIG_MISSING_INDICATORS', 'ELIGIBILITY', 'Eligibility tidak dapat ditentukan karena indikator wajib tidak tersedia.', 'HARD', 1),
('ELIG_INVALID_INDICATORS', 'ELIGIBILITY', 'Row indikator tersedia tetapi status indikator wajib ditandai tidak valid.', 'WARN', 1),
('ELIG_INSUFFICIENT_HISTORY', 'ELIGIBILITY', 'Eligibility ditolak karena riwayat yang dibutuhkan untuk indikator wajib belum mencukupi.', 'WARN', 1),
('ELIG_UNIVERSE_DEPENDENCY_MISSING', 'ELIGIBILITY', 'Dependency upstream yang dibutuhkan untuk membentuk membership universe tidak tersedia.', 'HARD', 1),
('ELIG_FETCH_FAILURE', 'ELIGIBILITY', 'Eligibility ditolak karena akuisisi source pada level ticker gagal sehingga artefak upstream yang dibutuhkan tidak dapat dibentuk dengan aman.', 'WARN', 1),
('SNAP_SOURCE_TIMEOUT', 'INTRADAY', 'Source untuk session snapshot mengalami timeout.', 'WARN', 1),
('SNAP_SOURCE_RATE_LIMIT', 'INTRADAY', 'Source untuk session snapshot terkena rate limit.', 'WARN', 1),
('SNAP_PARTIAL_SCOPE', 'INTRADAY', 'Session snapshot hanya berhasil menangkap sebagian scope yang direncanakan.', 'WARN', 1),
('SNAP_SOURCE_ERROR', 'INTRADAY', 'Source untuk session snapshot gagal karena alasan operasional yang tidak memblokir EOD.', 'WARN', 1)
ON DUPLICATE KEY UPDATE
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `severity` = VALUES(`severity`),
  `is_active` = VALUES(`is_active`);