-- REASON_CODES_SEED.sql
-- Policy: WS_EOD_PLAN_CONFIRM
-- Table: watchlist_reason_codes(reason_code PK, scope, severity, short_id, description_id, description_en)

-- Tabel global watchlist_reason_codes dibuat oleh: ../../db/04_DB_SEED_GLOBAL.sql
INSERT INTO watchlist_reason_codes (policy_code, reason_code, scope, severity, short_id, description_id, description_en) VALUES
('WS','WS_DATA_MISSING','PLAN','BLOCK','data_missing',
 'Data wajib tidak lengkap untuk ticker ini (field input minimal tidak tersedia).',
 'Required input fields are missing for this ticker.'),
('WS','WS_HIST_SHORT','PLAN','BLOCK','hist_short', 
 'Histori data tidak cukup (min_history_days) sehingga ticker ditolak.', 
 'Insufficient history (min_history_days); ticker rejected.'),
('WS','WS_MISSING_BARS_60D','PLAN','BLOCK','missing_bars_60d', 
 'Data OHLC bolong melebihi batas pada 60 hari trading terakhir.', 
 'Missing OHLC bars exceed limit in last 60 trading days.'),
('WS','WS_OUTLIER_RET1D','PLAN','BLOCK','outlier_ret1d', 
 'Outlier return 1 hari melebihi batas.', 
 '1D return outlier exceeds limit.'),
('WS','WS_OUTLIER_RANGE1D','PLAN','BLOCK','outlier_range1d', 
 'Outlier range high-low 1 hari melebihi batas.', 
 '1D high-low range outlier exceeds limit.'),
('WS','WS_MOM_SOFT_MIN','PLAN','WARN','mom_soft_min', 
 'Momentum (ROC20) di bawah ambang soft; skor momentum dinolkan.', 
 'Momentum (ROC20) below soft threshold; momentum score zeroed.'),
('WS','WS_DATA_OUTLIER','PLAN','BLOCK','data_outlier',
 'Terdeteksi bar outlier (indikasi data korup/tidak wajar) sehingga ticker ditolak.',
 'Outlier bar detected (potential corrupt/unusual data), ticker rejected.'),
('WS','WS_EOD_ABORT','PLAN','BLOCK','eod_abort',
 'Batch data EOD dianggap tidak lengkap; PLAN dibatalkan (fail-fast).',
 'EOD batch considered incomplete; PLAN aborted (fail-fast).'),

('WS','WS_LIQ_FAIL','PLAN','BLOCK','liq_fail',
 'Likuiditas gagal: dv20 di bawah batas minimum.',
 'Liquidity failed: dv20 below minimum threshold.'),
('WS','WS_ATR_LOW','PLAN','BLOCK','atr_low',
 'Volatilitas terlalu rendah (ATR% di bawah batas minimum).',
 'Volatility too low (ATR% below minimum).'),
('WS','WS_ATR_HIGH','PLAN','BLOCK','atr_high',
 'Volatilitas terlalu tinggi (ATR% di atas batas maksimum).',
 'Volatility too high (ATR% above maximum).'),

('WS','WS_MOM_STRONG','PLAN','INFO','mom_strong',
 'Momentum kuat (ROC20 tinggi).',
 'Strong momentum (high ROC20).'),
('WS','WS_MOM_WEAK','PLAN','WARN','mom_weak',
 'Momentum lemah (ROC20 rendah).',
 'Weak momentum (low ROC20).'),

('WS','WS_BO_NEAR','PLAN','INFO','bo_near',
 'Dekat level breakout (masih di bawah HH20 tetapi sudah mendekat).',
 'Near breakout (below HH20 but close).'),
('WS','WS_BO_BREAK','PLAN','INFO','bo_break',
 'Sedang/baru breakout (close di atas HH20 dan belum terlalu extended).',
 'Breaking out (close above HH20, not too extended).'),
('WS','WS_BO_FAR','PLAN','WARN','bo_far',
 'Masih jauh dari level breakout (di bawah HH20 dan belum mendekat).',
 'Far from breakout level (below HH20, not near).'),
('WS','WS_BO_EXT','PLAN','WARN','bo_ext',
 'Sudah terlalu extended di atas HH20 (risiko chasing).',
 'Too extended above HH20 (chasing risk).'),

('WS','WS_LIQ_STRONG','PLAN','INFO','liq_strong',
 'Likuiditas kuat (dv20 tinggi).',
 'Strong liquidity (high dv20).'),
('WS','WS_LIQ_BORDER','PLAN','WARN','liq_border',
 'Likuiditas borderline (dv20 lolos minimum namun tidak kuat).',
 'Borderline liquidity (passes minimum but not strong).'),

('WS','WS_RISK_IDEAL','PLAN','INFO','risk_ideal',
 'Volatilitas berada di rentang ideal.',
 'Volatility within ideal range.'),
('WS','WS_RISK_HIGH','PLAN','WARN','risk_high',
 'Volatilitas cenderung tinggi (risiko stopout/drawdown lebih besar).',
 'Volatility tends high (higher stopout/drawdown risk).'),
('WS','WS_RISK_LOW','PLAN','WARN','risk_low',
 'Volatilitas cenderung rendah (potensi lambat bergerak).',
 'Volatility tends low (may move slowly).'),

('WS','WS_FW_EXT','PLAN','WARN','fw_ext',
 'Dipaksa WATCH_ONLY: harga terlalu extended, hindari chasing.',
 'Forced WATCH_ONLY: too extended, avoid chasing.'),
('WS','WS_FW_RR_LOW','PLAN','WARN','fw_rr_low',
 'Dipaksa WATCH_ONLY: risk-reward tidak memenuhi minimum.',
 'Forced WATCH_ONLY: risk-reward below minimum.'),
('WS','WS_FW_RR_INV','PLAN','WARN','fw_rr_inv',
 'Dipaksa WATCH_ONLY: perhitungan stop/TP/RR tidak valid.',
 'Forced WATCH_ONLY: invalid stop/TP/RR computation.'),

('WS','WS_GRP_TOP','PLAN','INFO','grp_top',
 'Masuk grup TOP_PICKS berdasarkan kualitas setup.',
 'Classified into TOP_PICKS based on setup quality.'),
('WS','WS_GRP_SEC','PLAN','INFO','grp_sec',
 'Masuk grup SECONDARY berdasarkan kualitas setup.',
 'Classified into SECONDARY based on setup quality.'),
('WS','WS_GRP_WATCH','PLAN','INFO','grp_watch',
 'Masuk grup WATCH_ONLY (monitoring / tidak prioritas eksekusi).',
 'Classified into WATCH_ONLY (monitoring / not primary for execution).'),
('WS','WS_GRP_AVOID','PLAN','INFO','grp_avoid',
 'Masuk grup AVOID (ditolak oleh guard/data readiness atau kualitas sangat rendah).',
 'Classified into AVOID (rejected by guards/readiness or very low quality).'),

('WS','WS_SEL_PCT','PLAN','INFO','sel_pct',
 'Dipilih tampil karena masuk kuota persentil teratas dan lolos ambang skor.',
 'Selected for display due to top percentile quota and passing score thresholds.'),
('WS','WS_HID_PCT','PLAN','INFO','hid_pct',
 'Lolos ambang skor, tetapi tidak masuk kuota persentil; disembunyikan untuk menjaga fokus.',
 'Passed score thresholds but outside percentile quota; hidden for focus.'),
('WS','WS_HID_CAP','PLAN','INFO','hid_cap',
 'Disembunyikan karena batas tampilan (cap) untuk menjaga keterbacaan.',
 'Hidden due to display cap to keep list readable.'),
('WS','WS_SHOW','PLAN','INFO','show',
 'Masuk daftar tampil (SHOW).',
 'Included in display list (SHOW).'),
('WS','WS_HIDE','PLAN','INFO','hide',
 'Tidak ditampilkan (HIDE), namun tetap tersimpan untuk audit.',
 'Not displayed (HIDE) but preserved for audit.'),
('WS','WS_RUN_CAPPED','PLAN','WARN','run_capped',
 'Jumlah kandidat melebihi batas tampilan; sebagian disembunyikan.',
 'Candidates exceeded display cap; some were hidden.'),

('WS','WS_NO_TRADE_MIN_ELIGIBLE','PLAN','INFO','no_trade_min_eligible',
 'Run valid tetapi tidak menampilkan kandidat karena jumlah eligible lebih kecil dari batas minimum.',
 'Valid run with no displayed candidates because eligible count is below the minimum threshold.'),

('WS','WS_PLAN_HASH_MISMATCH','PLAN','BLOCK','plan_hash_mismatch',
 'Hash PLAN berubah setelah CONFIRM atau setelah proses audit; ini melanggar invariant immutability.',
 'PLAN hash changed after CONFIRM or audit process; this violates the immutability invariant.'),

('WS','WS_PLAN_WRITEBACK_DETECTED','PLAN','BLOCK','plan_writeback',
 'Terdeteksi operasi tulis ke persistence PLAN saat proses CONFIRM; ini melanggar DB write-scope contract.',
 'Detected write operation to PLAN persistence during CONFIRM; violates DB write-scope contract.'),

('WS','WS_SNAPSHOT_MISSING','CONFIRM','BLOCK','snap_missing',
 'Snapshot intraday belum diinput; CONFIRM tidak bisa dijalankan.',
 'Intraday snapshot not provided; confirm cannot run.'),
('WS','WS_STALE','CONFIRM','BLOCK','stale',
 'Data runtime terlalu tua (stale), hasil CONFIRM tidak bisa dipercaya.',
 'Runtime data too old (stale), confirm cannot be trusted.'),
('WS','WS_NO_PRICE','CONFIRM','BLOCK','no_price',
 'Harga runtime tidak tersedia, tidak bisa menghitung drift.',
 'Runtime price missing; cannot compute drift.'),

('WS','WS_DRIFT_FAR','CONFIRM','WARN','drift_far',
 'Harga runtime terlalu jauh dari entry band (indikasi chasing atau sudah lari).',
 'Runtime price too far from entry band (chasing or already moved).'),
('WS','WS_OUT_BAND','CONFIRM','WARN','out_band',
 'Harga runtime berada di luar entry band.',
 'Runtime price is outside entry band.'),
('WS','WS_SPR_WIDE','CONFIRM','WARN','spr_wide',
 'Spread terlalu lebar (eksekusi berisiko jelek).',
 'Spread too wide (poor execution risk).'),
('WS','WS_SPR_NA','CONFIRM','INFO','spr_na',
 'Data bid/ask tidak diinput; spread tidak dievaluasi.',
 'Bid/ask not provided; spread not evaluated.'),